Merge templates
wmo-im/csv2bufr pull request #118
Opened 2023-09-01 13:13 UTC by david-i-berry

Merge of csv2bufr_templates and csv2bufr modules.
- Templates can now be loaded with csv2bufr.templates.load_template()
- Default templates provided
- User defined path for templates added (CSV2BUFR_TEMPLATES=...)

2023-09-01 13:14 UTC, david-i-berry commented
@tomkralidis @maaikelimper I've refactored where the default templates are in the module. I don't know if these are used in the wis2box but something to be aware off when reviewing.

2023-09-04 23:03 UTC, tomkralidis requested changes

2023-09-04 23:03 UTC, tomkralidis commented on csv2bufr/templates/__init__.py
> +                with open(template_file, 'r') as fh:
```python
with template_file.open() as fh:
```

2023-09-04 23:03 UTC, tomkralidis commented on csv2bufr/templates/__init__.py
> +    for dir in TEMPLATE_DIRS:
`dir_`

2023-09-04 23:03 UTC, tomkralidis commented on csv2bufr/templates/__init__.py
> +            _templates = os.listdir(dir)
Suggest to use pathlib's `iterdir` generator.

```python
for template in dir_.iterdir():
```

2023-09-04 23:03 UTC, tomkralidis commented on csv2bufr/templates/__init__.py
> +def load_template(template_name):
Add docstring and function annotations.

2023-09-04 23:03 UTC, tomkralidis commented on csv2bufr/templates/__init__.py
> +def list_templates():
Add docstring and function annotations.

2023-09-04 23:04 UTC, tomkralidis commented
Thanks @david-i-berry. To confirm, https://github.com/wmo-im/csv2bufr-templates is now not to be used?  Should this repo be set to archived mode then?

2023-09-05 09:07 UTC, david-i-berry commented
> Thanks @david-i-berry. To confirm, https://github.com/wmo-im/csv2bufr-templates is now not to be used? Should this repo be set to archived mode then?

Yes, I'll mark it to archived now and add a note.

2023-09-05 10:12 UTC, tomkralidis approved these changes

2023-09-05 10:12 UTC, merged