Basename
wmo-im/csv2bufr pull request #130
Opened 2024-02-13 14:52 UTC by david-i-berry

Addition of basename to objects returned by list_templates.

2024-02-13 15:09 UTC, maaikelimper approved these changes

2024-02-13 17:20 UTC, tomkralidis requested changes

2024-02-14 08:57 UTC, david-i-berry commented on csv2bufr/templates/__init__.py
> +                                "basename": Path(fname).name.replace(".json", "")  # noqa
Done.

2024-02-14 12:35 UTC, tomkralidis approved these changes

2024-02-14 15:13 UTC, merged